# -*- coding: utf-8 -*-
"""Introducción a Python I

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FI2ShNOvyRGL4YSEOHZIXD4xVqBz07gQ
"""

'''
Este es el primer programa de introduccion a python
revisiones
historial cambios
parametros
'''

# Este es el primer adios mundo
print("Adios Mundo!") # Comentario inline
print("Hola Mundo!")

var_int = 7
print(var_int, type(var_int))
var_dec = 7.0
print(var_dec, type(var_dec))
var_cadena = 'Hola'
print(var_cadena, type(var_cadena))
a,b = 3,4
print(a)
print(b)
print(a+b)

"""**TIPO DE DATOS**

***NUMERICO***
"""

a = -1
b = a + 2
print(b,type(b))

var_dec1 = 10.1
var_dec2 = 2.2
resultado = var_dec1 * var_dec2
print(resultado, type(resultado))

complejo = 1 + 2j
print(complejo.real)
print(complejo.imag)

"""***BOOLEANO***"""

varA = True
varB = False
print(varA)

x = 24
varT = x > 20
varF = x < 20
print(varT)
print(varF)

"""***CADENAS***"""

var1 = "Hola Python"
var2 = ", este es el primer modulo"
varRes = var1 + var2
print(varRes,type(varRes))

print(var1[0])
print(var1[5])
print(len(var1))
print(len(varRes))

"""***LISTAS***"""

lista_10 = [1,2,3,4,5,6,7,8,9,10]
print(lista_10,type(lista_10))

lista_comb = [3,"a",8,7.2,"hola"]
print(lista_comb,type(lista_comb))

lista_comb2 = [1,2,3,'hola','adios',['a','e','i',4,5],1.5]
print(lista_comb2)

lista1 = list('HolaPython')
print(lista1)
print(len(lista1))
print(lista1[0])
print(lista1[9])
print(lista1[-1])
print(lista1[-4])
print(lista1[0:3])
print(lista1[3:])
print(lista1[-3:])

lista1 = lista1 + [2023,11]
print(lista1)

lista1.append(28)
print(lista1)

lista1.append([21,'horas'])
print(lista1)

lista1.extend([21,'horas'])
print(lista1)

lista1.count('o') #Contar ocurrencias
'y' in lista1 #True
'q' in lista1 #False

del lista1[13]

print(lista1)

"""***TUPLAS***"""

tupla1 = (1,2,3,4,5)
print(tupla1,type(tupla1))

tupla2 = tuple('aeiou')
print(tupla2, type(tupla2))

tupla1[0]
tupla2[3]

"""***DICCIONARIOS***"""

dict1 = {
    'hola':'python',
    2023:'año',
    'mes':11
}
print(dict1,type(dict1))

print(dict1[2023])

dict1.pop(2023) # remover elemento
print(dict1)

dict1['año']=2023 # añadir nuevo elemento
print(dict1)

dict2 = {
    'uno':1,
    'dos':2,
    'tres':3
}
print(dict2['dos'])
print(dict2.keys())
print(dict2.values())

dict2['tres'] = 30
print(dict2)

dict2.pop('uno') # remover un valor del diccionario

print(dict2)

"""***OPERACIONES BÁSICAS***"""

var = 1+2+3+4+5+6+7+8+9+10 # 55
var = var -5 # 50
var = var // 4  # 12 coef division
var = var % 5 # 2 resto division
var = var ** 6 # 64 potencia --pow(var,6)
var = var ** 0.5 # 8 raiz.   --pow(var,1/2)
print(var)

var_str = "Hola" + " " + "Python" + ", "
var_str = var_str * 3
print(var_str)

ls_var = list(var_str)
del ls_var[-2]
print(ls_var)

"del" in "Hola Python Noviembre del 2023"

"2024" in "Hola Python Noviembre del 2023"

'10' in [1,2,3,4,5,6,7,8,9,10,'hola','python']

5 in [1,2,3,4,5,6,7,8,9,10,'hola','python']

var_bool = "del" in "Hola Python Noviembre del 2023"
print(var_bool)

"""***INSTRUCCIONES DE CONTROL***

***IF***
"""

x = 15

if x<0:
  print("Valor negativo")
elif x<10:
  print("Valor positivo menor a 10")
elif x<20:
  print("Valor positivo menor a 20")
else:
  print("Valor positivo")

"""***EJERCICIO (SLIDE 38):***

Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.
"""

### SOLUCION ###
nombre = "Andrea"
sexo = "mujer"

if (sexo == "mujer" and nombre[0].lower() < 'm') or (sexo == "hombre" and nombre[0].lower() > 'n'):
  grupo = "A"
else:
  grupo = "B"

print(grupo)

"""***WHILE***"""

# while condition
#   body of while loop
i = 1
while i < 6:
  print(i)
  i += 1

# break
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

#continue
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

"""***FOR***"""

# for element in iterable:
#   tu codigo

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

for x in "banana":
  print(x)

for x in range(6):
  print(x)

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)
  if x == "banana":
    break

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]
for x in adj:
  for y in fruits:
    print(x, y)

"""***EJERCICIO (SLIDE 46):***

Escribir un programa que pida al usuario un número entero y muestre por pantalla un triángulo rectángulo como el de más abajo, de altura el número introducido.

                         *
                         **
                         ***
                         ****
                         *****
"""

### SOLUCION ###

# Supongamos que el usuario introduce el número 5
numero = 5

# Construir el triángulo rectángulo
for i in range(1, numero + 1):
    print("*" * i)